feat!: Highlight timestamp as util.inspect hightlights Dates
gulpjs/fancy-log pull request #23
Opened 2021-12-27 22:26 UTC by phated

This also drops ansi-gray and timestamp in favor of using the platform.

Closes #18 (because they can configure the logging - see README)

@sttk please review! Will this help you support color theme on the timestamp when logging in gulp-cli?

2022-01-04 18:41 UTC, phated commented
@sttk please review this when you have some time.

2022-01-04 18:43 UTC, yocontra commented on README.md
> +## Stying
```suggestion
## Styling
```

2022-01-07 14:33 UTC, sttk requested changes, later dismissed
@phated Sorry for the lay reply. I reviewed this PR and I found a slight mistake.

There is no other problem. Great!

2022-01-07 14:33 UTC, sttk commented on README.md
> +var utils = require('utils');
```suggestion
var util = require('util');
```

2022-01-07 18:50 UTC, phated commented on README.md
> +var utils = require('utils');
Good catch! Thank you

2022-01-07 18:58 UTC, merged